import Message from '../models/Message.js';
import nodemailer from 'nodemailer';

export const submitMessage = async (req, res) => {
  const { name, email, message } = req.body;

  try {
    if (!name || !email || !message) {
      return res.status(400).json({ message: 'All fields are required.' });
    }

    const newMessage = await Message.create({ name, email, message });

    // Send email notification
    try {
      const transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 587,
        secure: false, 
        auth: {
          user: 'ayutawebsite@gmail.com',
          pass: 'oxndcwvbonklvgvx', // App password
        },
      });

      // Template Teks Biasa (Plain Text) yang lebih terstruktur
      const textTemplate = `
=========================================
  NEW CONTACT MESSAGE - AYUTA.ID
=========================================

You have received a new message from your website contact form.

👤 Name    : ${name}
✉️ Email   : ${email}

📝 Message :
-----------------------------------------
${message}
-----------------------------------------

* This is an automated notification.
      `.trim();

      // Template HTML yang modern dan profesional
      const htmlTemplate = `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f4f5; padding: 40px 20px; color: #3f3f46;">
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
            
            <!-- Header -->
            <div style="background-color: #18181b; padding: 25px 30px; text-align: center;">
              <h2 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 600; letter-spacing: 0.5px;">
                New Contact Submission
              </h2>
            </div>
            
            <!-- Body -->
            <div style="padding: 30px;">
              <p style="font-size: 15px; color: #52525b; margin-top: 0; margin-bottom: 25px; line-height: 1.6;">
                You have received a new message from the <strong>Ayuta.id</strong> contact form. Here are the details:
              </p>
              
              <table style="width: 100%; border-collapse: collapse; margin-bottom: 25px;">
                <tr>
                  <td style="padding: 12px 0; border-bottom: 1px solid #e4e4e7; width: 120px; color: #71717a; font-size: 14px;"><strong>Name</strong></td>
                  <td style="padding: 12px 0; border-bottom: 1px solid #e4e4e7; color: #18181b; font-size: 15px; font-weight: 500;">${name}</td>
                </tr>
                <tr>
                  <td style="padding: 12px 0; border-bottom: 1px solid #e4e4e7; color: #71717a; font-size: 14px;"><strong>Email</strong></td>
                  <td style="padding: 12px 0; border-bottom: 1px solid #e4e4e7; font-size: 15px;">
                    <a href="mailto:${email}" style="color: #2563eb; text-decoration: none; font-weight: 500;">${email}</a>
                  </td>
                </tr>
              </table>
              
              <div>
                <strong style="display: block; margin-bottom: 10px; color: #71717a; font-size: 14px;">Message:</strong>
                <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; font-size: 15px; line-height: 1.7; color: #334155; white-space: pre-wrap;">${message}</div>
              </div>
            </div>
            
            <!-- Footer -->
            <div style="background-color: #fafafa; padding: 20px; text-align: center; border-top: 1px solid #f4f4f5;">
              <p style="margin: 0; font-size: 12px; color: #a1a1aa;">
                This is an automated message generated by the Ayuta.id system.<br/>
                Please reply directly to the user's email address if needed.
              </p>
            </div>
            
          </div>
        </div>
      `;

      const mailOptions = {
        from: `"${name} via Ayuta.id" <ayutawebsite@gmail.com>`, 
        replyTo: email,
        to: 'mail@ayuta.id',
        subject: `Ayuta.id New Message from ${name}`,
        text: textTemplate,
        html: htmlTemplate, 
      };

      await transporter.sendMail(mailOptions);
    } catch (emailError) {
      console.error('Failed to send email notification:', emailError);
    }

    return res.status(201).json({ message: 'Message sent successfully.', data: newMessage });
  } catch (error) {
    return res.status(500).json({ message: 'Server error.', error: error.message });
  }
};

export const getAllMessages = async (req, res) => {
  try {
    const messages = await Message.findAll({ order: [['createdAt', 'DESC']] });
    return res.status(200).json(messages);
  } catch (error) {
    return res.status(500).json({ message: 'Server error.', error: error.message });
  }
};

export const deleteMessage = async (req, res) => {
  const { id } = req.params;

  try {
    const message = await Message.findByPk(id);
    if (!message) {
      return res.status(404).json({ message: 'Message not found.' });
    }

    await message.destroy();
    return res.status(200).json({ message: 'Message deleted successfully.' });
  } catch (error) {
    return res.status(500).json({ message: 'Server error.', error: error.message });
  }
};